### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by januszjasinski** [laggyalbedo/ctf#1]
This does not work

**Comment by ksl-fourwalls** [comment]
which one ?

**Comment by ksl-fourwalls** [comment]
I think you may be talking about dice ctf challenge babyrop It works locally perfectly but when communicate with server, then server is closing the connection due to which this doesn't work. 
I planned of sending stream of input (as buffered) but program doesn't accept for some reason.

**Comment by januszjasinski** [comment]
Yes sorry, dice

**Comment by januszjasinski** [comment]
DIdn't work locally for me either. Maybe same issue

**Comment by ksl-fourwalls** [comment]
Flag is not imp :^) 
Learn too much by implementing locally
